[package]
name = "hns"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib", "rlib"]

[profile.wasm-release]
lto = true
panic = "abort"
opt-level = 'z'
codegen-units = 1
inherits = "release"

[dependencies]
serde_json = "1.0"
leptos_meta = "0.8"
leptos_router = "0.8"
serde = { version = "1", features = ["derive"] }
chrono = { version = "0.4", features = ["serde"] }
leptos = { version = "0.8", features = ["nightly"] }
web-sys = { version = "0.3", features = ["Storage"] }

log = { version = "0.4", optional = true }
anyhow = { version = "1", optional = true }
axum = { version = "0.8", optional = true }
sled = { version = "0.34", optional = true }
thiserror = { version = "2", optional = true }
tracing = { version = "0.1", optional = true }
futures = { version = "0.3", optional = true }
dashmap = { version = "6.1", optional = true }
rust-embed = { version = "8", optional = true }
mime_guess = { version = "2", optional = true }
scraper = { version = "0.27", optional = true }
wasm-bindgen = { version = "0.2", optional = true }
leptos_axum = { version = "0.8", optional = true }
tokio-stream = { version = "0.1", optional = true }
platform-dirs = { version = "0.3", optional = true }
uuid = { version = "1", features = ["v4"], optional = true }
tokio = { version = "1", features = ["full"], optional = true }
console_error_panic_hook = { version = "0.1", optional = true }
server_fn = { version = "0.8", features = ["axum"], optional = true }
clap = { version = "4", features = ["derive", "env"], optional = true }
tower-http = { version = "0.7", features = ["cors", "fs"], optional = true }

tracing-subscriber = { version = "0.3", features = [
  "env-filter",
], optional = true }

reqwest = { version = "0.13", default-features = false, features = [
  "json",
  "charset",
  "stream",
  "rustls-no-provider",
  "socks",
], optional = true }

rustls = { version = "0.23", default-features = false, features = [
  "ring",
  "std",
  "tls12",
  "logging",
], optional = true }

hyper-rustls = { version = "0.27", default-features = false, features = [
  "ring",
  "native-tokio",
  "http1",
  "tls12",
  "logging",
], optional = true }

tokio-rustls = { version = "0.26", default-features = false, features = [
  "ring",
  "tls12",
  "logging",
], optional = true }


[features]
default = ["ssr"]
hydrate = ["leptos/hydrate", "dep:console_error_panic_hook", "dep:wasm-bindgen"]
ssr = [
  "dep:axum",
  "dep:tokio",
  "dep:tower-http",
  "dep:leptos_axum",
  "dep:sled",
  "dep:clap",
  "dep:platform-dirs",
  "dep:rust-embed",
  "dep:mime_guess",
  "dep:dashmap",
  "dep:uuid",
  "dep:reqwest",
  "dep:rustls",
  "dep:hyper-rustls",
  "dep:tokio-rustls",
  "dep:scraper",
  "dep:log",
  "dep:tracing",
  "dep:tracing-subscriber",
  "dep:anyhow",
  "dep:thiserror",
  "dep:futures",
  "dep:tokio-stream",
  "leptos/ssr",
  "leptos_meta/ssr",
  "leptos_router/ssr",
  "server_fn/axum",
]

[package.metadata.leptos]
env = "DEV"
output-name = "hns"
site-root = "target/site"
site-pkg-dir = "pkg"
assets-dir = "public"
site-addr = "127.0.0.1:3000"
reload-port = 3001
bin-features = ["ssr"]
bin-default-features = false
lib-features = ["hydrate"]
lib-default-features = false
lib-profile-release = "wasm-release"
